# Site settings
author: Dasha Lary
title: Dasha's coding journey
header-img: img/home-bg.png
email: dk2800@nyu.edu
copyright_name: Dasha Lary
description: > # this means to ignore newlines until "baseurl:"
  My coding blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dashalary

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
